[tool.poetry]
name = "clairmeta"
version = "1.5.1"
description = "ClairMeta is a python package for Digital Cinema Package (DCP) probing and checking."
authors = ["RÃ©mi Achard <remiachard@gmail.com>"]
license = "BSD-3-Clause"
readme = "README.rst"

[tool.poetry.dependencies]
python = "^3.8"
lxml = "^4.9.3"
dicttoxml = "^1.7.16"
xmltodict = "^0.13.0"
python-dateutil = "^2.8.2"
six = "^1.16.0"
pyopenssl = "^23.2.0"
pycountry = "^22.3.5"
shutilwhich = "^1.1.0"
cryptography = "^41.0.4"
freetype-py = "^2.4.0"


[tool.poetry.group.dev.dependencies]
coverage = "^7.3.2"
pytest = "^7.4.2"
ruff = "^0.0.292"
black = "^23.9.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
